// <auto-generated> Generated by tools/gen_levels.py from the web build's level data. Do not edit by hand. </auto-generated>
using System.Collections.Generic;

namespace CyberRider.Core
{
    public static class Levels
    {
        public static readonly RegionDef[] Regions =
        {
            new RegionDef { Id = "peaks", Name = "Neon Peaks", Environment = "mountain", Blurb = "Downhill speed. Learn the line.", MapX = 0.08, MapY = 0.62 },
            new RegionDef { Id = "glacier", Name = "Glacier Grid", Environment = "glacier", Blurb = "Frictionless shelves and an avalanche.", MapX = 0.22, MapY = 0.32 },
            new RegionDef { Id = "dunes", Name = "Dune Circuit", Environment = "desert", Blurb = "Crosswinds, cannons and fragile cargo.", MapX = 0.36, MapY = 0.66 },
            new RegionDef { Id = "forest", Name = "Data Forest", Environment = "forest", Blurb = "Springy canopies and stranded techs.", MapX = 0.5, MapY = 0.38 },
            new RegionDef { Id = "skyline", Name = "Skyline District", Environment = "rooftops", Blurb = "Precision ledges, rails and demolition.", MapX = 0.62, MapY = 0.7 },
            new RegionDef { Id = "undercity", Name = "Undercity", Environment = "cave", Blurb = "Darkness, magnets and a collapsing tower.", MapX = 0.74, MapY = 0.4 },
            new RegionDef { Id = "lunar", Name = "Lunar Relay", Environment = "moon", Blurb = "Low gravity, big air, a rolling moonball.", MapX = 0.86, MapY = 0.66 },
            new RegionDef { Id = "machine", Name = "The Machine", Environment = "machine", Blurb = "Gears, belts, pendulums and the core.", MapX = 0.94, MapY = 0.3 },
        };

        public static readonly List<LevelDef> All = new List<LevelDef>
        {
            Peaks1(),
            Peaks2(),
            Peaks3(),
            Peaks4(),
            Glacier1(),
            Glacier2(),
            Glacier3(),
            Glacier4(),
            Dunes1(),
            Dunes2(),
            Dunes3(),
            Dunes4(),
            Forest1(),
            Forest2(),
            Forest3(),
            Forest4(),
            Roof1(),
            Roof2(),
            Roof3(),
            Roof4(),
            Cave1(),
            Cave2(),
            Cave3(),
            Cave4(),
            Moon1(),
            Moon2(),
            Moon3(),
            Moon4(),
            Machine1(),
            Machine2(),
            Machine3(),
            Machine4(),
        };

        public static LevelDef ById(string id)
        {
            foreach (var l in All) if (l.Id == id) return l;
            return null;
        }

        public static LevelDef Next(string id)
        {
            int i = All.FindIndex(l => l.Id == id);
            if (i < 0 || i >= All.Count - 1) return null;
            return All[i + 1];
        }

        public static List<LevelDef> InRegion(string region)
        {
            var list = new List<LevelDef>();
            foreach (var l in All) if (l.Region == region) list.Add(l);
            return list;
        }

        private static LevelDef Peaks1()
        {
            var level = new LevelDef
            {
                Id = "peaks-1",
                Name = "First Descent",
                Region = "peaks",
                Environment = "mountain",
                Mode = "reach",
                Tagline = "Bridge the gap. Reach the glow.",
                Briefing = "Bosh starts on the ledge. The valley floor is down and to the right. Draw a line to carry him across the gap. Lines are one-sided: draw left to right so the top face is solid.",
                Budget = 45,
                Materials = new List<MaterialId> { MaterialId.Normal },
                Rider = null,
                Start = new Vec2d(0, 0),
                Finish = new Zone(560, 156, 44, 70),
                Zoom = 1.6,
                Focus = new Vec2d(300, 100),
            };
            level.Lines.Add(new LevelLine(-40, 6, 70, 12));
            level.Lines.Add(new LevelLine(240, 150, 470, 226));
            level.Lines.Add(new LevelLine(470, 226, 700, 226));
            level.Lines.Add(new LevelLine(700, 226, 760, 200));
            level.Lines.Add(new LevelLine(760, 200, 760, 100));
            level.Objectives.Add(new Objective("finish"));
            level.Objectives.Add(new Objective("inkUnder", 30, true));
            level.Objectives.Add(new Objective("noDeath", null, true));
            level.Objectives.Add(new Objective("timeUnder", 300, true));
            return level;
        }

        private static LevelDef Peaks2()
        {
            var level = new LevelDef
            {
                Id = "peaks-2",
                Name = "The Canyon",
                Region = "peaks",
                Environment = "mountain",
                Mode = "reach",
                Tagline = "Speed first. Then the jump.",
                Briefing = "A steep chute feeds a plateau that ends at a canyon. Shape a kicker at the edge so Bosh clears the drop, and give him somewhere soft to land.",
                Budget = 40,
                Materials = new List<MaterialId> { MaterialId.Normal, MaterialId.Accel },
                Rider = null,
                Start = new Vec2d(0, 0),
                Finish = new Zone(760, 20, 44, 70),
                Zoom = 1.4,
                Focus = new Vec2d(400, 80),
            };
            level.Lines.Add(new LevelLine(-40, 6, 60, 30));
            level.Lines.Add(new LevelLine(60, 30, 200, 140));
            level.Lines.Add(new LevelLine(200, 140, 360, 170));
            level.Lines.Add(new LevelLine(360, 170, 420, 170));
            level.Lines.Add(new LevelLine(640, 150, 700, 100));
            level.Lines.Add(new LevelLine(700, 100, 760, 90));
            level.Lines.Add(new LevelLine(760, 90, 900, 90));
            level.Lines.Add(new LevelLine(900, 90, 900, -20));
            level.Objectives.Add(new Objective("finish"));
            level.Objectives.Add(new Objective("airtime", 40, true));
            level.Objectives.Add(new Objective("inkUnder", 25, true));
            level.Objectives.Add(new Objective("noDeath", null, true));
            return level;
        }

        private static LevelDef Peaks3()
        {
            var level = new LevelDef
            {
                Id = "peaks-3",
                Name = "Three Flags",
                Region = "peaks",
                Environment = "mountain",
                Mode = "flags",
                Tagline = "Detours pay.",
                Briefing = "The main slope runs straight to the finish, but three flags hang off it. Build detours that grab every flag and still get Bosh home. Completing this unlocks Vex.",
                Budget = 110,
                Materials = new List<MaterialId> { MaterialId.Normal, MaterialId.Accel },
                Rider = null,
                Start = new Vec2d(0, 0),
                Finish = new Zone(1180, 250, 44, 70),
                Zoom = 1.1,
                Focus = new Vec2d(600, 160),
            };
            level.Flags.Add(new Vec2d(330, 60));
            level.Flags.Add(new Vec2d(700, 260));
            level.Flags.Add(new Vec2d(980, 140));
            level.Lines.Add(new LevelLine(-40, 6, 70, 12));
            level.Lines.Add(new LevelLine(140, 60, 260, 110));
            level.Lines.Add(new LevelLine(260, 110, 400, 150));
            level.Lines.Add(new LevelLine(520, 200, 620, 300));
            level.Lines.Add(new LevelLine(620, 300, 820, 300));
            level.Lines.Add(new LevelLine(820, 300, 900, 280));
            level.Lines.Add(new LevelLine(1040, 300, 1100, 320));
            level.Lines.Add(new LevelLine(1100, 320, 1300, 320));
            level.Lines.Add(new LevelLine(1300, 320, 1300, 200));
            level.Objectives.Add(new Objective("finish"));
            level.Objectives.Add(new Objective("flags", 3));
            level.Objectives.Add(new Objective("noDeath", null, true));
            level.Objectives.Add(new Objective("timeUnder", 700, true));
            return level;
        }

        private static LevelDef Peaks4()
        {
            var level = new LevelDef
            {
                Id = "peaks-4",
                Name = "Big Air",
                Region = "peaks",
                Environment = "mountain",
                Mode = "stunt",
                Tagline = "Send it. Land it.",
                Briefing = "The chute below is long and fast. Build a kicker, get Bosh upside down, and bring him back onto the landing. A flip only counts once he lands on the board.",
                Budget = 70,
                Materials = new List<MaterialId> { MaterialId.Normal, MaterialId.Accel, MaterialId.Booster },
                Rider = null,
                Start = new Vec2d(0, 0),
                Finish = new Zone(1100, 330, 50, 80),
                Zoom = 1.2,
                Focus = new Vec2d(550, 200),
            };
            level.Lines.Add(new LevelLine(-40, 6, 80, 40));
            level.Lines.Add(new LevelLine(80, 40, 260, 210));
            level.Lines.Add(new LevelLine(260, 210, 420, 260));
            level.Lines.Add(new LevelLine(420, 260, 520, 262));
            level.Lines.Add(new LevelLine(760, 300, 900, 400));
            level.Lines.Add(new LevelLine(900, 400, 1200, 410));
            level.Lines.Add(new LevelLine(1200, 410, 1200, 300));
            level.Objectives.Add(new Objective("flips", 1));
            level.Objectives.Add(new Objective("finish"));
            level.Objectives.Add(new Objective("airtime", 80, true));
            level.Objectives.Add(new Objective("trickScore", 1200, true));
            level.Objectives.Add(new Objective("noDeath", null, true));
            return level;
        }

        private static LevelDef Glacier1()
        {
            var level = new LevelDef
            {
                Id = "glacier-1",
                Name = "Zero Friction",
                Region = "glacier",
                Environment = "glacier",
                Mode = "reach",
                Tagline = "Nothing slows down here.",
                Briefing = "Every surface on the glacier is frictionless. Speed only ever grows. Get Bosh from the shelf to the finish without letting the speed turn into a crash.",
                Budget = 60,
                Materials = new List<MaterialId> { MaterialId.Normal, MaterialId.Ice, MaterialId.Sticky },
                Rider = null,
                Start = new Vec2d(0, 0),
                Finish = new Zone(900, 260, 44, 70),
                Zoom = 1.3,
                Focus = new Vec2d(450, 150),
            };
            level.Lines.Add(new LevelLine(-40, 6, 120, 40, "ice"));
            level.Lines.Add(new LevelLine(120, 40, 300, 130, "ice"));
            level.Lines.Add(new LevelLine(300, 130, 380, 140, "ice"));
            level.Lines.Add(new LevelLine(560, 220, 720, 330, "ice"));
            level.Lines.Add(new LevelLine(720, 330, 1000, 330, "ice"));
            level.Lines.Add(new LevelLine(1000, 330, 1000, 230, "ice"));
            level.Objectives.Add(new Objective("finish"));
            level.Objectives.Add(new Objective("inkUnder", 35, true));
            level.Objectives.Add(new Objective("timeUnder", 320, true));
            level.Objectives.Add(new Objective("noDeath", null, true));
            return level;
        }

        private static LevelDef Glacier2()
        {
            var level = new LevelDef
            {
                Id = "glacier-2",
                Name = "Crevasse",
                Region = "glacier",
                Environment = "glacier",
                Mode = "puzzle",
                Tagline = "Fifty metres of ice. One crevasse.",
                Briefing = "A deep crevasse splits the shelf. You have very little ink. Crumble lines are cheap but vanish after a touch; use them where Bosh only needs a moment of support. Completing this unlocks Tank.",
                Budget = 50,
                Materials = new List<MaterialId> { MaterialId.Normal, MaterialId.Crumble, MaterialId.Accel },
                Rider = null,
                Start = new Vec2d(0, 0),
                Finish = new Zone(1020, 60, 44, 70),
                Zoom = 1.2,
                Focus = new Vec2d(500, 100),
            };
            level.Lines.Add(new LevelLine(-40, 6, 200, 40, "ice"));
            level.Lines.Add(new LevelLine(200, 40, 340, 60, "ice"));
            level.Lines.Add(new LevelLine(340, 400, 340, 60, "ice"));
            level.Lines.Add(new LevelLine(660, 400, 660, 120, "ice"));
            level.Lines.Add(new LevelLine(660, 120, 800, 130, "ice"));
            level.Lines.Add(new LevelLine(800, 130, 1100, 130, "ice"));
            level.Lines.Add(new LevelLine(1100, 130, 1100, 30, "ice"));
            level.Objectives.Add(new Objective("finish"));
            level.Objectives.Add(new Objective("inkUnder", 38, true));
            level.Objectives.Add(new Objective("noDeath", null, true));
            return level;
        }

        private static LevelDef Glacier3()
        {
            var level = new LevelDef
            {
                Id = "glacier-3",
                Name = "Sticky Situation",
                Region = "glacier",
                Environment = "glacier",
                Mode = "puzzle",
                Tagline = "Arrive slow or not at all.",
                Briefing = "The finish sits on a narrow ledge at the bottom of a sheer drop with a wall behind it. Bosh will arrive screaming fast. Use sticky and spring surfaces to bleed speed before the ledge.",
                Budget = 55,
                Materials = new List<MaterialId> { MaterialId.Normal, MaterialId.Sticky, MaterialId.Spring, MaterialId.Mud },
                Rider = null,
                Start = new Vec2d(0, 0),
                Finish = new Zone(700, 350, 40, 60),
                Zoom = 1.3,
                Focus = new Vec2d(400, 200),
            };
            level.Lines.Add(new LevelLine(-40, 6, 200, 120, "ice"));
            level.Lines.Add(new LevelLine(200, 120, 420, 260, "ice"));
            level.Lines.Add(new LevelLine(420, 260, 480, 270, "ice"));
            level.Lines.Add(new LevelLine(600, 410, 760, 410));
            level.Lines.Add(new LevelLine(760, 410, 760, 300));
            level.Lines.Add(new LevelLine(760, 300, 760, 410, "normal", true));
            level.Objectives.Add(new Objective("finish"));
            level.Objectives.Add(new Objective("noDeath", null, true));
            level.Objectives.Add(new Objective("inkUnder", 40, true));
            return level;
        }

        private static LevelDef Glacier4()
        {
            var level = new LevelDef
            {
                Id = "glacier-4",
                Name = "Avalanche",
                Region = "glacier",
                Environment = "glacier",
                Mode = "boss",
                Tagline = "It is faster than you think.",
                Briefing = "The whole shelf is coming down behind you. Bridge the gaps before you press play, then keep Bosh moving. Accel lines are your friend; sticky patches are not. If the wall catches him, it is over.",
                Budget = 120,
                Materials = new List<MaterialId> { MaterialId.Normal, MaterialId.Accel, MaterialId.Ice, MaterialId.Booster },
                Rider = null,
                Start = new Vec2d(0, 0),
                Finish = new Zone(1900, 380, 50, 90),
                Zoom = 1,
                Focus = new Vec2d(900, 220),
            };
            level.Flags.Add(new Vec2d(620, 150));
            level.Flags.Add(new Vec2d(1300, 300));
            level.Lines.Add(new LevelLine(-40, 6, 200, 60, "ice"));
            level.Lines.Add(new LevelLine(200, 60, 400, 110, "ice"));
            level.Lines.Add(new LevelLine(400, 110, 500, 120, "ice"));
            level.Lines.Add(new LevelLine(700, 180, 900, 220, "ice"));
            level.Lines.Add(new LevelLine(900, 220, 1000, 230, "ice"));
            level.Lines.Add(new LevelLine(1200, 320, 1450, 360, "ice"));
            level.Lines.Add(new LevelLine(1450, 360, 1550, 370, "ice"));
            level.Lines.Add(new LevelLine(1750, 470, 2100, 470, "ice"));
            level.Lines.Add(new LevelLine(2100, 470, 2100, 360, "ice"));
            level.Entities.Add(new EntityDef { Type = "avalanche", StartX = -900, Speed = 6.2, Delay = 30, Accel = 0.004 });
            level.Objectives.Add(new Objective("finish"));
            level.Objectives.Add(new Objective("flags", 2, true));
            level.Objectives.Add(new Objective("inkUnder", 90, true));
            return level;
        }

        private static LevelDef Dunes1()
        {
            var level = new LevelDef
            {
                Id = "dunes-1",
                Name = "Crosswind",
                Region = "dunes",
                Environment = "desert",
                Mode = "reach",
                Tagline = "The air has opinions.",
                Briefing = "Gusts sweep across the dunes and shove the rider whenever he leaves the ground. Keep jumps short or aim them into the wind. Watch the streaks: they show which way it blows.",
                Budget = 70,
                Materials = new List<MaterialId> { MaterialId.Normal, MaterialId.Accel },
                Rider = null,
                Start = new Vec2d(0, 0),
                Finish = new Zone(1000, 210, 44, 70),
                Zoom = 1.2,
                Focus = new Vec2d(500, 140),
            };
            level.Lines.Add(new LevelLine(-40, 6, 120, 60));
            level.Lines.Add(new LevelLine(120, 60, 260, 100));
            level.Lines.Add(new LevelLine(260, 100, 340, 100));
            level.Lines.Add(new LevelLine(480, 160, 600, 180));
            level.Lines.Add(new LevelLine(600, 180, 640, 180));
            level.Lines.Add(new LevelLine(800, 240, 960, 280));
            level.Lines.Add(new LevelLine(960, 280, 1100, 280));
            level.Lines.Add(new LevelLine(1100, 280, 1100, 180));
            level.Objectives.Add(new Objective("finish"));
            level.Objectives.Add(new Objective("noDeath", null, true));
            level.Objectives.Add(new Objective("inkUnder", 50, true));
            return level;
        }

        private static LevelDef Dunes2()
        {
            var level = new LevelDef
            {
                Id = "dunes-2",
                Name = "Cannon Run",
                Region = "dunes",
                Environment = "desert",
                Mode = "reach",
                Tagline = "Ride in. Fly out.",
                Briefing = "A cannon sits at the bottom of the first dune. Roll Bosh into it and it fires him at 40 degrees. Your ink goes on the far side: he needs a landing, and the finish is above the mesa.",
                Budget = 60,
                Materials = new List<MaterialId> { MaterialId.Normal, MaterialId.Accel, MaterialId.Spring },
                Rider = null,
                Start = new Vec2d(0, 0),
                Finish = new Zone(1040, 30, 44, 70),
                Zoom = 1.2,
                Focus = new Vec2d(550, 100),
            };
            level.Lines.Add(new LevelLine(-40, 6, 100, 60));
            level.Lines.Add(new LevelLine(100, 60, 220, 120));
            level.Lines.Add(new LevelLine(220, 120, 300, 130));
            level.Lines.Add(new LevelLine(780, 100, 1000, 100));
            level.Lines.Add(new LevelLine(1000, 100, 1150, 100));
            level.Lines.Add(new LevelLine(1150, 100, 1150, 0));
            level.Lines.Add(new LevelLine(300, 130, 400, 220));
            level.Lines.Add(new LevelLine(400, 220, 700, 220));
            level.Entities.Add(new EntityDef { Type = "cannon", X = 330, Y = 122, Angle = -40, Power = 11 });
            level.Objectives.Add(new Objective("finish"));
            level.Objectives.Add(new Objective("airtime", 60, true));
            level.Objectives.Add(new Objective("noDeath", null, true));
            return level;
        }

        private static LevelDef Dunes3()
        {
            var level = new LevelDef
            {
                Id = "dunes-3",
                Name = "Express Delivery",
                Region = "dunes",
                Environment = "desert",
                Mode = "delivery",
                Tagline = "Handle with care.",
                Briefing = "A fragile crate is strapped to the back of the board. Every hard landing and jolt chips at it, and a violent enough hit tears it off entirely. Smooth curves beat fast drops.",
                Budget = 120,
                Materials = new List<MaterialId> { MaterialId.Normal, MaterialId.Mud, MaterialId.Sticky },
                Rider = null,
                Start = new Vec2d(0, 0),
                Finish = new Zone(1100, 300, 50, 80),
                Zoom = 1.2,
                Focus = new Vec2d(600, 200),
            };
            level.Lines.Add(new LevelLine(-40, 6, 160, 40));
            level.Lines.Add(new LevelLine(160, 40, 300, 60));
            level.Lines.Add(new LevelLine(560, 200, 700, 240));
            level.Lines.Add(new LevelLine(700, 240, 820, 250));
            level.Lines.Add(new LevelLine(980, 370, 1220, 380));
            level.Lines.Add(new LevelLine(1220, 380, 1220, 280));
            level.Objectives.Add(new Objective("cargo", 50));
            level.Objectives.Add(new Objective("cargo", 85, true));
            level.Objectives.Add(new Objective("timeUnder", 600, true));
            return level;
        }

        private static LevelDef Dunes4()
        {
            var level = new LevelDef
            {
                Id = "dunes-4",
                Name = "Rockslide",
                Region = "dunes",
                Environment = "desert",
                Mode = "boss",
                Tagline = "The cliff is letting go.",
                Briefing = "Crossing the marker triggers a rockfall from the cliff above. Rocks roll, bounce and follow gravity like everything else. Build your route so the rocks miss him, or so he is long gone.",
                Budget = 100,
                Materials = new List<MaterialId> { MaterialId.Normal, MaterialId.Accel, MaterialId.Spring },
                Rider = null,
                Start = new Vec2d(0, 0),
                Finish = new Zone(1200, 300, 50, 80),
                Zoom = 1.1,
                Focus = new Vec2d(650, 150),
            };
            level.Lines.Add(new LevelLine(-40, 6, 120, 50));
            level.Lines.Add(new LevelLine(120, 50, 260, 110));
            level.Lines.Add(new LevelLine(260, 110, 380, 140));
            level.Lines.Add(new LevelLine(380, 140, 500, 150));
            level.Lines.Add(new LevelLine(500, 150, 700, 260));
            level.Lines.Add(new LevelLine(700, 260, 900, 330));
            level.Lines.Add(new LevelLine(900, 330, 1000, 350));
            level.Lines.Add(new LevelLine(1000, 350, 1300, 380));
            level.Lines.Add(new LevelLine(1300, 380, 1300, 280));
            level.Lines.Add(new LevelLine(560, -80, 780, -40));
            level.Entities.Add(new EntityDef { Type = "rockfall", X = 680, Y = -70, Count = 5, Spread = 30, Trigger = 420, Radius = 8 });
            level.Objectives.Add(new Objective("finish"));
            level.Objectives.Add(new Objective("noDeath", null, true));
            level.Objectives.Add(new Objective("timeUnder", 500, true));
            return level;
        }

        private static LevelDef Forest1()
        {
            var level = new LevelDef
            {
                Id = "forest-1",
                Name = "Canopy Bounce",
                Region = "forest",
                Environment = "forest",
                Mode = "reach",
                Tagline = "The trees push back.",
                Briefing = "Spring canopies fling the rider back the way he came in. Angle your drop so the bounce sends Bosh up and to the right, and be ready for the second one.",
                Budget = 60,
                Materials = new List<MaterialId> { MaterialId.Normal, MaterialId.Spring },
                Rider = null,
                Start = new Vec2d(0, 0),
                Finish = new Zone(860, 40, 44, 70),
                Zoom = 1.3,
                Focus = new Vec2d(450, 120),
            };
            level.Lines.Add(new LevelLine(-40, 6, 70, 12));
            level.Lines.Add(new LevelLine(220, 240, 340, 200, "spring"));
            level.Lines.Add(new LevelLine(560, 260, 680, 220, "spring"));
            level.Lines.Add(new LevelLine(800, 110, 960, 110));
            level.Lines.Add(new LevelLine(960, 110, 960, 10));
            level.Objectives.Add(new Objective("finish"));
            level.Objectives.Add(new Objective("airtime", 100, true));
            level.Objectives.Add(new Objective("inkUnder", 40, true));
            return level;
        }

        private static LevelDef Forest2()
        {
            var level = new LevelDef
            {
                Id = "forest-2",
                Name = "Search Party",
                Region = "forest",
                Environment = "forest",
                Mode = "rescue",
                Tagline = "Nobody gets left behind.",
                Briefing = "Three technicians are stranded in the canopy. Bosh has to pass close enough to scoop each one up, then reach the finish with everyone aboard. Reaching them means leaving the main line and reconnecting later.",
                Budget = 150,
                Materials = new List<MaterialId> { MaterialId.Normal, MaterialId.Accel, MaterialId.Spring },
                Rider = null,
                Start = new Vec2d(0, 0),
                Finish = new Zone(1300, 320, 50, 80),
                Zoom = 1.05,
                Focus = new Vec2d(700, 200),
            };
            level.Rescues.Add(new Vec2d(380, 40));
            level.Rescues.Add(new Vec2d(720, 330));
            level.Rescues.Add(new Vec2d(1040, 180));
            level.Lines.Add(new LevelLine(-40, 6, 70, 12));
            level.Lines.Add(new LevelLine(200, 120, 320, 160));
            level.Lines.Add(new LevelLine(320, 160, 480, 190));
            level.Lines.Add(new LevelLine(640, 340, 800, 340));
            level.Lines.Add(new LevelLine(960, 240, 1100, 280));
            level.Lines.Add(new LevelLine(1240, 400, 1420, 400));
            level.Lines.Add(new LevelLine(1420, 400, 1420, 300));
            level.Objectives.Add(new Objective("rescue", 3));
            level.Objectives.Add(new Objective("noDeath", null, true));
            level.Objectives.Add(new Objective("inkUnder", 110, true));
            return level;
        }

        private static LevelDef Forest3()
        {
            var level = new LevelDef
            {
                Id = "forest-3",
                Name = "Balance",
                Region = "forest",
                Environment = "forest",
                Mode = "puzzle",
                Tagline = "Weight tips the beam.",
                Briefing = "A seesaw bridges the ravine and a balloon waits beyond it. The beam tilts under Bosh, so where he lands decides where he leaves. Grab the balloon to float up to the finish.",
                Budget = 45,
                Materials = new List<MaterialId> { MaterialId.Normal },
                Rider = null,
                Start = new Vec2d(0, 0),
                Finish = new Zone(900, 60, 44, 70),
                Zoom = 1.3,
                Focus = new Vec2d(500, 120),
            };
            level.Lines.Add(new LevelLine(-40, 6, 120, 60));
            level.Lines.Add(new LevelLine(120, 60, 200, 80));
            level.Lines.Add(new LevelLine(560, 220, 680, 230));
            level.Lines.Add(new LevelLine(860, 130, 1000, 130));
            level.Lines.Add(new LevelLine(1000, 130, 1000, 30));
            level.Entities.Add(new EntityDef { Type = "seesaw", X = 380, Y = 140, Length = 160 });
            level.Entities.Add(new EntityDef { Type = "balloon", X = 760, Y = 200, Lift = 0.34, Duration = 120 });
            level.Objectives.Add(new Objective("finish"));
            level.Objectives.Add(new Objective("inkUnder", 30, true));
            level.Objectives.Add(new Objective("noDeath", null, true));
            return level;
        }

        private static LevelDef Forest4()
        {
            var level = new LevelDef
            {
                Id = "forest-4",
                Name = "Updraft",
                Region = "forest",
                Environment = "forest",
                Mode = "reach",
                Tagline = "Ride the fans.",
                Briefing = "Vent fans blow straight up through the canopy. Drop Bosh into a column and he rises; leave it and gravity takes over. Chain the columns to reach the finish high on the right.",
                Budget = 70,
                Materials = new List<MaterialId> { MaterialId.Normal, MaterialId.Accel },
                Rider = null,
                Start = new Vec2d(0, 0),
                Finish = new Zone(940, -140, 44, 70),
                Zoom = 1.1,
                Focus = new Vec2d(550, 0),
            };
            level.Lines.Add(new LevelLine(-40, 6, 70, 12));
            level.Lines.Add(new LevelLine(180, 160, 300, 200));
            level.Lines.Add(new LevelLine(300, 200, 420, 210));
            level.Lines.Add(new LevelLine(900, -70, 1060, -70));
            level.Lines.Add(new LevelLine(1060, -70, 1060, -170));
            level.Entities.Add(new EntityDef { Type = "fan", X = 430, Y = -200, W = 90, H = 420, Fx = 0.02, Fy = -0.42 });
            level.Entities.Add(new EntityDef { Type = "fan", X = 700, Y = -260, W = 90, H = 420, Fx = 0.03, Fy = -0.42 });
            level.Objectives.Add(new Objective("finish"));
            level.Objectives.Add(new Objective("airtime", 160, true));
            level.Objectives.Add(new Objective("noDeath", null, true));
            return level;
        }

        private static LevelDef Roof1()
        {
            var level = new LevelDef
            {
                Id = "roof-1",
                Name = "Ledge Runner",
                Region = "skyline",
                Environment = "rooftops",
                Mode = "puzzle",
                Tagline = "Twenty-five metres. Make them count.",
                Briefing = "Rooftop to rooftop with almost no ink. Each ledge is a little lower than the last, so momentum does most of the work if the exits are clean.",
                Budget = 25,
                Materials = new List<MaterialId> { MaterialId.Normal },
                Rider = null,
                Start = new Vec2d(0, 0),
                Finish = new Zone(760, 130, 40, 60),
                Zoom = 1.4,
                Focus = new Vec2d(400, 100),
            };
            level.Lines.Add(new LevelLine(-40, 6, 140, 30));
            level.Lines.Add(new LevelLine(220, 70, 360, 80));
            level.Lines.Add(new LevelLine(440, 120, 580, 130));
            level.Lines.Add(new LevelLine(660, 190, 860, 190));
            level.Lines.Add(new LevelLine(860, 190, 860, 90));
            level.Lines.Add(new LevelLine(140, 30, 180, 30));
            level.Lines.Add(new LevelLine(180, 42, 180, 430));
            level.Lines.Add(new LevelLine(180, 430, 140, 430));
            level.Lines.Add(new LevelLine(140, 430, 140, 42));
            level.Lines.Add(new LevelLine(360, 80, 400, 80));
            level.Lines.Add(new LevelLine(400, 92, 400, 480));
            level.Lines.Add(new LevelLine(400, 480, 360, 480));
            level.Lines.Add(new LevelLine(360, 480, 360, 92));
            level.Lines.Add(new LevelLine(580, 130, 620, 130));
            level.Lines.Add(new LevelLine(620, 142, 620, 530));
            level.Lines.Add(new LevelLine(620, 530, 580, 530));
            level.Lines.Add(new LevelLine(580, 530, 580, 142));
            level.Objectives.Add(new Objective("finish"));
            level.Objectives.Add(new Objective("inkUnder", 18, true));
            level.Objectives.Add(new Objective("noDeath", null, true));
            return level;
        }

        private static LevelDef Roof2()
        {
            var level = new LevelDef
            {
                Id = "roof-2",
                Name = "Grind City",
                Region = "skyline",
                Environment = "rooftops",
                Mode = "stunt",
                Tagline = "Rails score. Ledges do not.",
                Briefing = "Grind rails are frictionless and every second on one pays out. Link the rails with your ink, keep Bosh on them, and reach the finish with a trick score to match. Completing this unlocks Nova.",
                Budget = 80,
                Materials = new List<MaterialId> { MaterialId.Normal, MaterialId.Rail, MaterialId.Accel },
                Rider = null,
                Start = new Vec2d(0, 0),
                Finish = new Zone(1200, 260, 44, 70),
                Zoom = 1.1,
                Focus = new Vec2d(600, 160),
            };
            level.Lines.Add(new LevelLine(-40, 6, 120, 40));
            level.Lines.Add(new LevelLine(200, 80, 420, 110, "rail"));
            level.Lines.Add(new LevelLine(520, 150, 780, 200, "rail"));
            level.Lines.Add(new LevelLine(860, 240, 1060, 300, "rail"));
            level.Lines.Add(new LevelLine(1120, 330, 1300, 330));
            level.Lines.Add(new LevelLine(1300, 330, 1300, 230));
            level.Objectives.Add(new Objective("finish"));
            level.Objectives.Add(new Objective("trickScore", 600));
            level.Objectives.Add(new Objective("trickScore", 1500, true));
            level.Objectives.Add(new Objective("noDeath", null, true));
            return level;
        }

        private static LevelDef Roof3()
        {
            var level = new LevelDef
            {
                Id = "roof-3",
                Name = "Train Hop",
                Region = "skyline",
                Environment = "rooftops",
                Mode = "reach",
                Tagline = "Timing is a material too.",
                Briefing = "Elevated trains shuttle across the gap. They carry whatever lands on them. Drop Bosh onto a roof at the right moment and let the train do the travelling.",
                Budget = 50,
                Materials = new List<MaterialId> { MaterialId.Normal, MaterialId.Accel },
                Rider = null,
                Start = new Vec2d(0, 0),
                Finish = new Zone(1000, 120, 44, 70),
                Zoom = 1.2,
                Focus = new Vec2d(550, 120),
            };
            level.Lines.Add(new LevelLine(-40, 6, 160, 40));
            level.Lines.Add(new LevelLine(160, 40, 240, 50));
            level.Lines.Add(new LevelLine(960, 190, 1120, 190));
            level.Lines.Add(new LevelLine(1120, 190, 1120, 90));
            level.Entities.Add(new EntityDef { Type = "train", X = 380, Y = 160, W = 120, H = 30, Speed = 2.4, Range = 460 });
            level.Entities.Add(new EntityDef { Type = "train", X = 800, Y = 260, W = 100, H = 30, Speed = -1.8, Range = 380 });
            level.Objectives.Add(new Objective("finish"));
            level.Objectives.Add(new Objective("inkUnder", 30, true));
            level.Objectives.Add(new Objective("noDeath", null, true));
            return level;
        }

        private static LevelDef Roof4()
        {
            var level = new LevelDef
            {
                Id = "roof-4",
                Name = "Demolition",
                Region = "skyline",
                Environment = "rooftops",
                Mode = "destruction",
                Tagline = "Maximum chaos.",
                Briefing = "The rooftop is stacked with dominoes, crates and explosives. Draw a track, launch Bosh, and see how much of it you can bring down. Chaos is scored by everything you knock loose or blow up.",
                Budget = 90,
                Materials = new List<MaterialId> { MaterialId.Normal, MaterialId.Accel, MaterialId.Booster },
                Rider = null,
                Start = new Vec2d(0, 0),
                TimeLimit = 30,
                Zoom = 1.1,
                Focus = new Vec2d(550, 60),
            };
            level.Lines.Add(new LevelLine(-40, 6, 100, 40));
            level.Lines.Add(new LevelLine(100, 40, 220, 120));
            level.Lines.Add(new LevelLine(220, 120, 1000, 120));
            level.Lines.Add(new LevelLine(1000, 120, 1000, -100));
            level.Lines.Add(new LevelLine(1000, 120, 1300, 120));
            level.Props.Add(new PropDef { Kind = "domino", X = 320, Y = 108, Width = 4, Height = 24, Mass = 0.5 });
            level.Props.Add(new PropDef { Kind = "domino", X = 345, Y = 108, Width = 4, Height = 24, Mass = 0.5 });
            level.Props.Add(new PropDef { Kind = "domino", X = 370, Y = 108, Width = 4, Height = 24, Mass = 0.5 });
            level.Props.Add(new PropDef { Kind = "domino", X = 395, Y = 108, Width = 4, Height = 24, Mass = 0.5 });
            level.Props.Add(new PropDef { Kind = "domino", X = 420, Y = 108, Width = 4, Height = 24, Mass = 0.5 });
            level.Props.Add(new PropDef { Kind = "crate", X = 520, Y = 110, Width = 20, Height = 20, Mass = 1.5 });
            level.Props.Add(new PropDef { Kind = "crate", X = 520, Y = 90, Width = 20, Height = 20, Mass = 1.5 });
            level.Props.Add(new PropDef { Kind = "crate", X = 542, Y = 110, Width = 20, Height = 20, Mass = 1.5 });
            level.Props.Add(new PropDef { Kind = "tnt", X = 640, Y = 111, Width = 18, Height = 18, Mass = 1, Explosive = true });
            level.Props.Add(new PropDef { Kind = "crate", X = 700, Y = 110, Width = 20, Height = 20, Mass = 1.5 });
            level.Props.Add(new PropDef { Kind = "crate", X = 700, Y = 90, Width = 20, Height = 20, Mass = 1.5 });
            level.Props.Add(new PropDef { Kind = "crate", X = 700, Y = 70, Width = 20, Height = 20, Mass = 1.5 });
            level.Props.Add(new PropDef { Kind = "tnt", X = 800, Y = 111, Width = 18, Height = 18, Mass = 1, Explosive = true });
            level.Props.Add(new PropDef { Kind = "boulder", X = 900, Y = 106, Radius = 14, Mass = 6 });
            level.Props.Add(new PropDef { Kind = "domino", X = 960, Y = 108, Width = 4, Height = 24, Mass = 0.5 });
            level.Objectives.Add(new Objective("chaos", 1500));
            level.Objectives.Add(new Objective("chaos", 3500, true));
            level.Objectives.Add(new Objective("noDeath", null, true));
            return level;
        }

        private static LevelDef Cave1()
        {
            var level = new LevelDef
            {
                Id = "cave-1",
                Name = "Blackout",
                Region = "undercity",
                Environment = "cave",
                Mode = "reach",
                Tagline = "Draw from memory.",
                Briefing = "Only a small halo of light follows the rider. Scout the cave while editing, then trust the lines you drew. The finish glows, faintly, down and to the right.",
                Budget = 80,
                Materials = new List<MaterialId> { MaterialId.Normal, MaterialId.Accel },
                Rider = null,
                Start = new Vec2d(0, 0),
                Finish = new Zone(900, 300, 44, 70),
                Zoom = 1.2,
                Focus = new Vec2d(450, 180),
            };
            level.Lines.Add(new LevelLine(-40, 6, 70, 12));
            level.Lines.Add(new LevelLine(200, 120, 340, 160));
            level.Lines.Add(new LevelLine(340, 160, 420, 170));
            level.Lines.Add(new LevelLine(600, 250, 740, 300));
            level.Lines.Add(new LevelLine(860, 370, 1000, 370));
            level.Lines.Add(new LevelLine(1000, 370, 1000, 270));
            level.Lines.Add(new LevelLine(500, 60, 520, 200));
            level.Lines.Add(new LevelLine(520, 200, 540, 60));
            level.Objectives.Add(new Objective("finish"));
            level.Objectives.Add(new Objective("noDeath", null, true));
            level.Objectives.Add(new Objective("inkUnder", 55, true));
            return level;
        }

        private static LevelDef Cave2()
        {
            var level = new LevelDef
            {
                Id = "cave-2",
                Name = "Crumbling Depths",
                Region = "undercity",
                Environment = "cave",
                Mode = "reach",
                Tagline = "Everything here is temporary.",
                Briefing = "The old bridges give way segment by segment once touched. Keep moving, or draw your own way over them. Crumble ink is cheap if you only need a moment.",
                Budget = 90,
                Materials = new List<MaterialId> { MaterialId.Normal, MaterialId.Crumble, MaterialId.Accel },
                Rider = null,
                Start = new Vec2d(0, 0),
                Finish = new Zone(1100, 260, 44, 70),
                Zoom = 1.1,
                Focus = new Vec2d(600, 180),
            };
            level.Lines.Add(new LevelLine(-40, 6, 120, 50));
            level.Lines.Add(new LevelLine(120, 50, 200, 70));
            level.Lines.Add(new LevelLine(620, 200, 720, 220));
            level.Lines.Add(new LevelLine(1080, 330, 1200, 330));
            level.Lines.Add(new LevelLine(1200, 330, 1200, 230));
            level.Entities.Add(new EntityDef { Type = "bridge", X = 200, Y = 70, W = 420, Segments = 7, Delay = 8 });
            level.Entities.Add(new EntityDef { Type = "bridge", X = 720, Y = 220, W = 360, Segments = 6, Delay = 6 });
            level.Objectives.Add(new Objective("finish"));
            level.Objectives.Add(new Objective("inkUnder", 40, true));
            level.Objectives.Add(new Objective("timeUnder", 420, true));
            return level;
        }

        private static LevelDef Cave3()
        {
            var level = new LevelDef
            {
                Id = "cave-3",
                Name = "Magnet Mine",
                Region = "undercity",
                Environment = "cave",
                Mode = "puzzle",
                Tagline = "Attraction is not optional.",
                Briefing = "Magnetic cores pull the rider toward them within their field. One sits above the chasm: pass under it fast enough and it bends the arc instead of swallowing it.",
                Budget = 40,
                Materials = new List<MaterialId> { MaterialId.Normal, MaterialId.Accel },
                Rider = null,
                Start = new Vec2d(0, 0),
                Finish = new Zone(860, 180, 44, 70),
                Zoom = 1.3,
                Focus = new Vec2d(500, 120),
            };
            level.Lines.Add(new LevelLine(-40, 6, 160, 80));
            level.Lines.Add(new LevelLine(160, 80, 300, 140));
            level.Lines.Add(new LevelLine(300, 140, 360, 150));
            level.Lines.Add(new LevelLine(800, 250, 960, 250));
            level.Lines.Add(new LevelLine(960, 250, 960, 150));
            level.Entities.Add(new EntityDef { Type = "magnet", X = 580, Y = 40, Radius = 190, Strength = 0.09 });
            level.Objectives.Add(new Objective("finish"));
            level.Objectives.Add(new Objective("inkUnder", 25, true));
            level.Objectives.Add(new Objective("noDeath", null, true));
            return level;
        }

        private static LevelDef Cave4()
        {
            var level = new LevelDef
            {
                Id = "cave-4",
                Name = "Clock Tower",
                Region = "undercity",
                Environment = "cave",
                Mode = "boss",
                Tagline = "Descend before it falls.",
                Briefing = "The tower is coming apart on a timer. Floors drop in order from the top, gears keep turning. Get Bosh from the belfry down to the base before his floor goes.",
                Budget = 100,
                Materials = new List<MaterialId> { MaterialId.Normal, MaterialId.Accel, MaterialId.Crumble },
                Rider = null,
                Start = new Vec2d(0, 0),
                Finish = new Zone(560, 640, 50, 80),
                Zoom = 0.9,
                Focus = new Vec2d(280, 360),
            };
            level.Lines.Add(new LevelLine(-40, 6, 80, 20));
            level.Lines.Add(new LevelLine(80, 20, 160, 30));
            level.Lines.Add(new LevelLine(700, 720, 700, 0));
            level.Lines.Add(new LevelLine(-120, 0, -120, 720));
            level.Lines.Add(new LevelLine(-120, 720, 700, 720));
            level.Entities.Add(new EntityDef { Type = "collapse", X1 = 160, Y1 = 30, X2 = 560, Y2 = 60, At = 140 });
            level.Entities.Add(new EntityDef { Type = "collapse", X1 = 460, Y1 = 200, X2 = -20, Y2 = 230, At = 260 });
            level.Entities.Add(new EntityDef { Type = "collapse", X1 = 60, Y1 = 380, X2 = 560, Y2 = 400, At = 400 });
            level.Entities.Add(new EntityDef { Type = "gear", X = 300, Y = 300, Radius = 50, Teeth = 8, Speed = 0.02 });
            level.Entities.Add(new EntityDef { Type = "gear", X = 460, Y = 520, Radius = 40, Teeth = 7, Speed = -0.03 });
            level.Entities.Add(new EntityDef { Type = "collapse", X1 = 560, Y1 = 560, X2 = 200, Y2 = 580, At = 560 });
            level.Objectives.Add(new Objective("finish"));
            level.Objectives.Add(new Objective("timeUnder", 560, true));
            level.Objectives.Add(new Objective("noDeath", null, true));
            return level;
        }

        private static LevelDef Moon1()
        {
            var level = new LevelDef
            {
                Id = "moon-1",
                Name = "One Small Jump",
                Region = "lunar",
                Environment = "moon",
                Mode = "reach",
                Tagline = "Gravity at forty percent.",
                Briefing = "The moon pulls at less than half strength. Jumps go much further and everything floats, so lines that would be too short on Earth are suddenly generous.",
                Budget = 40,
                Materials = new List<MaterialId> { MaterialId.Normal },
                Rider = null,
                Start = new Vec2d(0, 0),
                Finish = new Zone(1100, 120, 44, 70),
                Zoom = 1.1,
                Focus = new Vec2d(600, 100),
            };
            level.Lines.Add(new LevelLine(-40, 6, 160, 60));
            level.Lines.Add(new LevelLine(160, 60, 300, 100));
            level.Lines.Add(new LevelLine(1000, 190, 1200, 190));
            level.Lines.Add(new LevelLine(1200, 190, 1200, 90));
            level.Objectives.Add(new Objective("finish"));
            level.Objectives.Add(new Objective("inkUnder", 20, true));
            level.Objectives.Add(new Objective("airtime", 100, true));
            return level;
        }

        private static LevelDef Moon2()
        {
            var level = new LevelDef
            {
                Id = "moon-2",
                Name = "Orbital",
                Region = "lunar",
                Environment = "moon",
                Mode = "stunt",
                Tagline = "Two flips. Take your time.",
                Briefing = "With this much hang time a single kicker can produce a double. Build the ramp, land two rotations, and bring him to the finish with the score to prove it.",
                Budget = 80,
                Materials = new List<MaterialId> { MaterialId.Normal, MaterialId.Accel, MaterialId.Booster },
                Rider = null,
                Start = new Vec2d(0, 0),
                Finish = new Zone(1300, 260, 50, 80),
                Zoom = 1,
                Focus = new Vec2d(700, 200),
            };
            level.Lines.Add(new LevelLine(-40, 6, 120, 60));
            level.Lines.Add(new LevelLine(120, 60, 360, 220));
            level.Lines.Add(new LevelLine(360, 220, 520, 250));
            level.Lines.Add(new LevelLine(520, 250, 620, 252));
            level.Lines.Add(new LevelLine(1000, 300, 1200, 340));
            level.Lines.Add(new LevelLine(1200, 340, 1400, 340));
            level.Lines.Add(new LevelLine(1400, 340, 1400, 240));
            level.Objectives.Add(new Objective("flips", 2));
            level.Objectives.Add(new Objective("finish"));
            level.Objectives.Add(new Objective("trickScore", 2500, true));
            level.Objectives.Add(new Objective("noDeath", null, true));
            return level;
        }

        private static LevelDef Moon3()
        {
            var level = new LevelDef
            {
                Id = "moon-3",
                Name = "Regolith Rescue",
                Region = "lunar",
                Environment = "moon",
                Mode = "rescue",
                Tagline = "Two survivors, one balloon.",
                Briefing = "Two crew members are stranded on crater rims. Balloons drift near each; grab one to float up and collect the survivor, then find a way back down to the finish.",
                Budget = 120,
                Materials = new List<MaterialId> { MaterialId.Normal, MaterialId.Accel },
                Rider = null,
                Start = new Vec2d(0, 0),
                Finish = new Zone(1200, 260, 50, 80),
                Zoom = 1,
                Focus = new Vec2d(650, 120),
            };
            level.Rescues.Add(new Vec2d(460, -60));
            level.Rescues.Add(new Vec2d(900, 60));
            level.Lines.Add(new LevelLine(-40, 6, 140, 60));
            level.Lines.Add(new LevelLine(140, 60, 300, 100));
            level.Lines.Add(new LevelLine(420, -50, 520, -50));
            level.Lines.Add(new LevelLine(600, 180, 760, 200));
            level.Lines.Add(new LevelLine(860, 70, 960, 70));
            level.Lines.Add(new LevelLine(1120, 340, 1320, 340));
            level.Lines.Add(new LevelLine(1320, 340, 1320, 240));
            level.Entities.Add(new EntityDef { Type = "balloon", X = 380, Y = 60, Lift = 0.14, Duration = 110 });
            level.Entities.Add(new EntityDef { Type = "balloon", X = 820, Y = 170, Lift = 0.14, Duration = 110 });
            level.Objectives.Add(new Objective("rescue", 2));
            level.Objectives.Add(new Objective("noDeath", null, true));
            level.Objectives.Add(new Objective("inkUnder", 80, true));
            return level;
        }

        private static LevelDef Moon4()
        {
            var level = new LevelDef
            {
                Id = "moon-4",
                Name = "Moonball",
                Region = "lunar",
                Environment = "moon",
                Mode = "boss",
                Tagline = "It only ever rolls toward you.",
                Briefing = "A colossal boulder is balanced above the crater rim. Cross the marker and it drops, then it keeps coming. Outrun it, jump it, or make it fall somewhere it cannot follow.",
                Budget = 130,
                Materials = new List<MaterialId> { MaterialId.Normal, MaterialId.Accel, MaterialId.Booster, MaterialId.Spring },
                Rider = null,
                Start = new Vec2d(0, 0),
                Finish = new Zone(1800, 380, 50, 90),
                Zoom = 0.9,
                Focus = new Vec2d(900, 250),
            };
            level.Lines.Add(new LevelLine(-40, 6, 160, 60));
            level.Lines.Add(new LevelLine(160, 60, 400, 160));
            level.Lines.Add(new LevelLine(400, 160, 600, 220));
            level.Lines.Add(new LevelLine(600, 220, 800, 260));
            level.Lines.Add(new LevelLine(800, 260, 1000, 300));
            level.Lines.Add(new LevelLine(1200, 380, 1400, 430));
            level.Lines.Add(new LevelLine(1400, 430, 1500, 450));
            level.Lines.Add(new LevelLine(1650, 470, 1950, 470));
            level.Lines.Add(new LevelLine(1950, 470, 1950, 370));
            level.Lines.Add(new LevelLine(-140, -60, -60, -40));
            level.Entities.Add(new EntityDef { Type = "snowball", X = -100, Y = -100, Radius = 34, Trigger = 200, Push = 0.09 });
            level.Objectives.Add(new Objective("finish"));
            level.Objectives.Add(new Objective("noDeath", null, true));
            level.Objectives.Add(new Objective("inkUnder", 100, true));
            return level;
        }

        private static LevelDef Machine1()
        {
            var level = new LevelDef
            {
                Id = "machine-1",
                Name = "Gearbox",
                Region = "machine",
                Environment = "machine",
                Mode = "reach",
                Tagline = "Teeth carry. Teeth also bite.",
                Briefing = "Spinning gears fill the chamber. Ride their rims in the direction they turn and they throw the board forward; land against the turn and they eat the speed.",
                Budget = 70,
                Materials = new List<MaterialId> { MaterialId.Normal, MaterialId.Accel },
                Rider = null,
                Start = new Vec2d(0, 0),
                Finish = new Zone(1000, 200, 44, 70),
                Zoom = 1.1,
                Focus = new Vec2d(550, 150),
            };
            level.Lines.Add(new LevelLine(-40, 6, 120, 60));
            level.Lines.Add(new LevelLine(120, 60, 200, 80));
            level.Lines.Add(new LevelLine(940, 270, 1100, 270));
            level.Lines.Add(new LevelLine(1100, 270, 1100, 170));
            level.Entities.Add(new EntityDef { Type = "gear", X = 380, Y = 200, Radius = 70, Teeth = 10, Speed = 0.025 });
            level.Entities.Add(new EntityDef { Type = "gear", X = 660, Y = 300, Radius = 90, Teeth = 12, Speed = 0.02 });
            level.Objectives.Add(new Objective("finish"));
            level.Objectives.Add(new Objective("noDeath", null, true));
            level.Objectives.Add(new Objective("inkUnder", 45, true));
            return level;
        }

        private static LevelDef Machine2()
        {
            var level = new LevelDef
            {
                Id = "machine-2",
                Name = "Belt Drive",
                Region = "machine",
                Environment = "machine",
                Mode = "reach",
                Tagline = "Some belts run the wrong way.",
                Briefing = "Conveyor surfaces drive the board toward a set speed along their arrow. Pistons rise and fall between them. Use the belts that help, jump the ones that do not.",
                Budget = 60,
                Materials = new List<MaterialId> { MaterialId.Normal, MaterialId.Conveyor, MaterialId.Accel },
                Rider = null,
                Start = new Vec2d(0, 0),
                Finish = new Zone(1200, 90, 44, 70),
                Zoom = 1.1,
                Focus = new Vec2d(650, 100),
            };
            level.Lines.Add(new LevelLine(-40, 6, 120, 60));
            level.Lines.Add(new LevelLine(200, 100, 440, 100, "conveyor"));
            level.Lines.Add(new LevelLine(820, 150, 600, 150, "conveyor"));
            level.Lines.Add(new LevelLine(1160, 160, 1300, 160));
            level.Lines.Add(new LevelLine(1300, 160, 1300, 60));
            level.Entities.Add(new EntityDef { Type = "platform", X = 520, Y = 130, W = 60, Dx = 0, Dy = 40, Period = 160 });
            level.Entities.Add(new EntityDef { Type = "platform", X = 980, Y = 200, W = 70, Dx = 0, Dy = 60, Period = 200, Phase = 1.5 });
            level.Objectives.Add(new Objective("finish"));
            level.Objectives.Add(new Objective("noDeath", null, true));
            level.Objectives.Add(new Objective("timeUnder", 500, true));
            return level;
        }

        private static LevelDef Machine3()
        {
            var level = new LevelDef
            {
                Id = "machine-3",
                Name = "Pendulum Hall",
                Region = "machine",
                Environment = "machine",
                Mode = "reach",
                Tagline = "Swing through.",
                Briefing = "Three hammers swing across the hall on different periods. Their heads are solid and moving; a hit from the side is a crash, a landing on top is a lift. Time your run.",
                Budget = 80,
                Materials = new List<MaterialId> { MaterialId.Normal, MaterialId.Accel, MaterialId.Booster },
                Rider = null,
                Start = new Vec2d(0, 0),
                Finish = new Zone(1200, 200, 44, 70),
                Zoom = 1,
                Focus = new Vec2d(650, 100),
            };
            level.Lines.Add(new LevelLine(-40, 6, 140, 60));
            level.Lines.Add(new LevelLine(140, 60, 260, 100));
            level.Lines.Add(new LevelLine(1140, 270, 1300, 270));
            level.Lines.Add(new LevelLine(1300, 270, 1300, 170));
            level.Entities.Add(new EntityDef { Type = "pendulum", X = 480, Y = -80, Length = 220, Width = 40, Amplitude = 0.9, Period = 180 });
            level.Entities.Add(new EntityDef { Type = "pendulum", X = 760, Y = -80, Length = 260, Width = 40, Amplitude = 0.8, Period = 220, Phase = 2 });
            level.Entities.Add(new EntityDef { Type = "pendulum", X = 1020, Y = -60, Length = 240, Width = 40, Amplitude = 0.7, Period = 160, Phase = 1 });
            level.Objectives.Add(new Objective("finish"));
            level.Objectives.Add(new Objective("noDeath", null, true));
            level.Objectives.Add(new Objective("nearMiss", 2, true));
            return level;
        }

        private static LevelDef Machine4()
        {
            var level = new LevelDef
            {
                Id = "machine-4",
                Name = "The Core",
                Region = "machine",
                Environment = "machine",
                Mode = "boss",
                Tagline = "Everything at once.",
                Briefing = "The core turns a wheel the size of a building. Gears, belts and a collapsing gantry surround it. Build a path around the machine, keep Bosh out of the teeth, and reach the exit before the gantry is gone.",
                Budget = 160,
                Materials = new List<MaterialId> { MaterialId.Normal, MaterialId.Accel, MaterialId.Booster, MaterialId.Conveyor, MaterialId.Crumble },
                Rider = null,
                Start = new Vec2d(0, 0),
                Finish = new Zone(1700, 420, 60, 100),
                Zoom = 0.8,
                Focus = new Vec2d(850, 280),
            };
            level.Lines.Add(new LevelLine(-40, 6, 160, 60));
            level.Lines.Add(new LevelLine(160, 60, 300, 90));
            level.Lines.Add(new LevelLine(1400, 480, 1600, 520));
            level.Lines.Add(new LevelLine(1600, 520, 1900, 520));
            level.Lines.Add(new LevelLine(1900, 520, 1900, 400));
            level.Lines.Add(new LevelLine(1100, 380, 1300, 380, "conveyor"));
            level.Entities.Add(new EntityDef { Type = "gear", X = 800, Y = 280, Radius = 200, Teeth = 20, Speed = 0.008 });
            level.Entities.Add(new EntityDef { Type = "gear", X = 420, Y = 330, Radius = 60, Teeth = 8, Speed = -0.03 });
            level.Entities.Add(new EntityDef { Type = "gear", X = 1180, Y = 120, Radius = 70, Teeth = 9, Speed = 0.03 });
            level.Entities.Add(new EntityDef { Type = "collapse", X1 = 300, Y1 = 90, X2 = 560, Y2 = 60, At = 200 });
            level.Entities.Add(new EntityDef { Type = "platform", X = 1000, Y = 470, W = 80, Dx = 0, Dy = 50, Period = 180 });
            level.Entities.Add(new EntityDef { Type = "bridge", X = 1300, Y = 380, W = 100, Segments = 4, Delay = 10 });
            level.Objectives.Add(new Objective("finish"));
            level.Objectives.Add(new Objective("noDeath", null, true));
            level.Objectives.Add(new Objective("timeUnder", 900, true));
            level.Objectives.Add(new Objective("inkUnder", 120, true));
            return level;
        }
    }
}
