import type { PublishedTrack } from '../game/library';
import type { TrackJSON } from '../game/track';

function json(lines: [number, number, number, number, string?][], start = { x: 0, y: 0 }, finish?: { x: number; y: number; w: number; h: number }): TrackJSON {
  return {
    version: 1,
    start,
    finish,
    nextId: lines.length + 1,
    lines: lines.map(([x1, y1, x2, y2, material], i) => ({
      id: i + 1,
      x1,
      y1,
      x2,
      y2,
      material: (material ?? 'normal') as TrackJSON['lines'][number]['material'],
      flipped: false,
      leftExt: false,
      rightExt: false,
      multiplier: 1,
      layer: 'player' as const,
      player: 0,
    })),
  };
}

/** Showcase tracks that ship with the game so the library is never empty. */
export const BUILTIN_TRACKS: PublishedTrack[] = [
  {
    id: 'builtin-halfpipe',
    title: 'Neon Halfpipe',
    author: 'Studio',
    description: 'A big bowl for practising flips and manuals. No budget, all materials unlocked.',
    tags: ['stunt', 'showcase', 'freeride'],
    difficulty: 2,
    environment: 'rooftops',
    budget: null,
    thumbnail: '',
    created: 1700000000000,
    likes: 12,
    plays: 0,
    liked: false,
    records: { bestFrames: null, bestInk: null, bestTrick: 0 },
    builtin: true,
    track: json([
      [-40, 6, 120, 30],
      [120, 30, 260, 120],
      [260, 120, 360, 170],
      [360, 170, 500, 190],
      [500, 190, 640, 170],
      [640, 170, 740, 120],
      [740, 120, 800, 40],
      [500, 190, 520, 190],
    ]),
  },
  {
    id: 'builtin-sprint',
    title: 'Booster Sprint',
    author: 'Studio',
    description: 'Straight-line speed with boosters. Race the clock to the finish.',
    tags: ['speed', 'race'],
    difficulty: 1,
    environment: 'mountain',
    budget: 60,
    thumbnail: '',
    created: 1700000001000,
    likes: 8,
    plays: 0,
    liked: false,
    records: { bestFrames: null, bestInk: null, bestTrick: 0 },
    builtin: true,
    track: json(
      [
        [-40, 6, 200, 40, 'accel'],
        [200, 40, 480, 120, 'accel'],
        [480, 120, 700, 160],
        [900, 220, 1200, 240],
        [1200, 240, 1200, 140],
      ],
      { x: 0, y: 0 },
      { x: 1100, y: 160, w: 50, h: 80 },
    ),
  },
  {
    id: 'builtin-drop',
    title: 'The Long Drop',
    author: 'Studio',
    description: 'Fifteen metres of ink, a cliff, and one landing. Survive it.',
    tags: ['puzzle', 'precision'],
    difficulty: 4,
    environment: 'cave',
    budget: 15,
    thumbnail: '',
    created: 1700000002000,
    likes: 21,
    plays: 0,
    liked: false,
    records: { bestFrames: null, bestInk: null, bestTrick: 0 },
    builtin: true,
    track: json(
      [
        [-40, 6, 140, 20],
        [300, 420, 600, 430],
        [600, 430, 600, 330],
      ],
      { x: 0, y: 0 },
      { x: 520, y: 350, w: 44, h: 70 },
    ),
  },
];
