"""Generate Assets/Scripts/Core/Game/Levels.cs and BuiltinTracks.cs from the JSON dumped by the web build."""
import json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, 'tools', 'CoreTests', 'data')
OUT = os.path.join(ROOT, 'Assets', 'Scripts', 'Core', 'Game')

def num(v):
    if isinstance(v, bool):
        return 'true' if v else 'false'
    if isinstance(v, int):
        return str(v)
    r = repr(float(v))
    if r.endswith('.0'):
        r = r[:-2]
    return r

def s(v):
    return '"' + v.replace('\\', '\\\\').replace('"', '\\"') + '"'

ENTITY_KEYS = {
    'x': 'X', 'y': 'Y', 'w': 'W', 'h': 'H', 'dx': 'Dx', 'dy': 'Dy', 'period': 'Period', 'phase': 'Phase',
    'material': 'Material', 'thickness': 'Thickness', 'radius': 'Radius', 'teeth': 'Teeth', 'speed': 'Speed',
    'length': 'Length', 'width': 'Width', 'amplitude': 'Amplitude', 'fx': 'Fx', 'fy': 'Fy', 'strength': 'Strength',
    'angle': 'Angle', 'power': 'Power', 'x1': 'X1', 'y1': 'Y1', 'x2': 'X2', 'y2': 'Y2', 'threshold': 'Threshold',
    'lift': 'Lift', 'duration': 'Duration', 'maxAngle': 'MaxAngle', 'range': 'Range', 'count': 'Count',
    'spread': 'Spread', 'trigger': 'Trigger', 'segments': 'Segments', 'delay': 'Delay', 'at': 'At',
    'startX': 'StartX', 'accel': 'Accel', 'push': 'Push', 'label': 'Label',
}
INT_KEYS = {'teeth', 'duration', 'count', 'segments', 'delay', 'at'}
MATERIAL_ENUM = {'normal': 'Normal', 'accel': 'Accel', 'scenery': 'Scenery', 'ice': 'Ice', 'mud': 'Mud', 'spring': 'Spring', 'sticky': 'Sticky', 'conveyor': 'Conveyor', 'crumble': 'Crumble', 'booster': 'Booster', 'oneway': 'OneWay', 'rail': 'Rail'}

def entity(e):
    parts = ['Type = ' + s(e['type'])]
    for k, v in e.items():
        if k == 'type':
            continue
        name = ENTITY_KEYS[k]
        if isinstance(v, str):
            parts.append(f'{name} = {s(v)}')
        elif k in INT_KEYS:
            parts.append(f'{name} = {int(v)}')
        else:
            parts.append(f'{name} = {num(v)}')
    return 'new EntityDef { ' + ', '.join(parts) + ' }'

def prop(p):
    parts = ['Kind = ' + s(p['kind'])]
    for k, name in [('x', 'X'), ('y', 'Y'), ('width', 'Width'), ('height', 'Height'), ('angle', 'Angle'), ('radius', 'Radius'), ('friction', 'Friction'), ('mass', 'Mass'), ('gravityScale', 'GravityScale')]:
        if k in p:
            parts.append(f'{name} = {num(p[k])}')
    if p.get('explosive'):
        parts.append('Explosive = true')
    if p.get('dormant'):
        parts.append('Dormant = true')
    return 'new PropDef { ' + ', '.join(parts) + ' }'

def line(l):
    args = [num(l['x1']), num(l['y1']), num(l['x2']), num(l['y2'])]
    if l.get('material') or l.get('flipped'):
        args.append(s(l['material']) if l.get('material') else 'null')
    if l.get('flipped'):
        args.append('true')
    out = 'new LevelLine(' + ', '.join(args) + ')'
    if l.get('multiplier') not in (None, 1):
        out += ' { Multiplier = ' + num(l['multiplier']) + ' }'
    return out

def objective(o):
    args = [s(o['kind'])]
    if 'value' in o:
        args.append(num(o['value']))
    elif o.get('optional') or o.get('label'):
        args.append('null')
    if o.get('optional'):
        args.append('true')
    elif o.get('label'):
        args.append('false')
    if o.get('label'):
        args.append(s(o['label']))
    return 'new Objective(' + ', '.join(args) + ')'

def method_name(level_id):
    return ''.join(part.capitalize() for part in level_id.replace('-', '_').split('_'))

data = json.load(open(os.path.join(DATA, 'levels.json')))
lines_out = []
w = lines_out.append
w('// <auto-generated> Generated by tools/gen_levels.py from the web build\'s level data. Do not edit by hand. </auto-generated>')
w('using System.Collections.Generic;')
w('')
w('namespace NeonLineRider.Core')
w('{')
w('    public static class Levels')
w('    {')
w('        public static readonly RegionDef[] Regions =')
w('        {')
for r in data['regions']:
    w(f'            new RegionDef {{ Id = {s(r["id"])}, Name = {s(r["name"])}, Environment = {s(r["environment"])}, Blurb = {s(r["blurb"])}, MapX = {num(r["mapX"])}, MapY = {num(r["mapY"])} }},')
w('        };')
w('')
w('        public static readonly List<LevelDef> All = new List<LevelDef>')
w('        {')
for lv in data['levels']:
    w(f'            {method_name(lv["id"])}(),')
w('        };')
w('')
w('        public static LevelDef ById(string id)')
w('        {')
w('            foreach (var l in All) if (l.Id == id) return l;')
w('            return null;')
w('        }')
w('')
w('        public static LevelDef Next(string id)')
w('        {')
w('            int i = All.FindIndex(l => l.Id == id);')
w('            if (i < 0 || i >= All.Count - 1) return null;')
w('            return All[i + 1];')
w('        }')
w('')
w('        public static List<LevelDef> InRegion(string region)')
w('        {')
w('            var list = new List<LevelDef>();')
w('            foreach (var l in All) if (l.Region == region) list.Add(l);')
w('            return list;')
w('        }')
for lv in data['levels']:
    w('')
    w(f'        private static LevelDef {method_name(lv["id"])}()')
    w('        {')
    w('            var level = new LevelDef')
    w('            {')
    w(f'                Id = {s(lv["id"])},')
    w(f'                Name = {s(lv["name"])},')
    w(f'                Region = {s(lv["region"])},')
    w(f'                Environment = {s(lv["environment"])},')
    w(f'                Mode = {s(lv["mode"])},')
    w(f'                Tagline = {s(lv["tagline"])},')
    w(f'                Briefing = {s(lv["briefing"])},')
    w(f'                Budget = {num(lv["budget"])},')
    w('                Materials = new List<MaterialId> { ' + ', '.join('MaterialId.' + MATERIAL_ENUM[m] for m in lv['materials']) + ' },')
    w(f'                Rider = {s(lv["rider"]) if lv.get("rider") else "null"},')
    w(f'                Start = new Vec2d({num(lv["start"]["x"])}, {num(lv["start"]["y"])}),')
    if lv.get('finish'):
        f = lv['finish']
        w(f'                Finish = new Zone({num(f["x"])}, {num(f["y"])}, {num(f["w"])}, {num(f["h"])}),')
    if lv.get('timeLimit'):
        w(f'                TimeLimit = {num(lv["timeLimit"])},')
    if lv.get('surviveFrames'):
        w(f'                SurviveFrames = {int(lv["surviveFrames"])},')
    if lv.get('zoom'):
        w(f'                Zoom = {num(lv["zoom"])},')
    if lv.get('focus'):
        w(f'                Focus = new Vec2d({num(lv["focus"]["x"])}, {num(lv["focus"]["y"])}),')
    w('            };')
    for fl in lv.get('flags', []):
        w(f'            level.Flags.Add(new Vec2d({num(fl["x"])}, {num(fl["y"])}));')
    for rs in lv.get('rescues', []):
        w(f'            level.Rescues.Add(new Vec2d({num(rs["x"])}, {num(rs["y"])}));')
    for l in lv['lines']:
        w(f'            level.Lines.Add({line(l)});')
    for e in lv.get('entities', []):
        w(f'            level.Entities.Add({entity(e)});')
    for p in lv.get('props', []):
        w(f'            level.Props.Add({prop(p)});')
    for o in lv['objectives']:
        w(f'            level.Objectives.Add({objective(o)});')
    w('            return level;')
    w('        }')
w('    }')
w('}')
open(os.path.join(OUT, 'Levels.cs'), 'w').write('\n'.join(lines_out) + '\n')

# Built-in tracks: embed the JSON verbatim and parse at startup.
builtins = json.load(open(os.path.join(DATA, 'builtin.json')))
b = []
b.append('// <auto-generated> Generated by tools/gen_levels.py. Do not edit by hand. </auto-generated>')
b.append('using System.Collections.Generic;')
b.append('')
b.append('namespace NeonLineRider.Core')
b.append('{')
b.append('    /// <summary>Showcase tracks that ship with the game so the library is never empty.</summary>')
b.append('    public static class BuiltinTracks')
b.append('    {')
b.append('        private static readonly string[] JsonSources =')
b.append('        {')
for t in builtins:
    js = json.dumps(t, separators=(',', ':'))
    b.append('            @"' + js.replace('"', '""') + '",')
b.append('        };')
b.append('')
b.append('        private static List<PublishedTrack> _all;')
b.append('')
b.append('        public static List<PublishedTrack> All')
b.append('        {')
b.append('            get')
b.append('            {')
b.append('                if (_all != null) return _all;')
b.append('                _all = new List<PublishedTrack>();')
b.append('                foreach (string src in JsonSources)')
b.append('                {')
b.append('                    var t = PublishedTrack.FromJson(Json.Obj(Json.Parse(src)));')
b.append('                    if (t != null) { t.Builtin = true; _all.Add(t); }')
b.append('                }')
b.append('                return _all;')
b.append('            }')
b.append('        }')
b.append('    }')
b.append('}')
open(os.path.join(OUT, 'BuiltinTracks.cs'), 'w').write('\n'.join(b) + '\n')
print('generated', len(data['levels']), 'levels and', len(builtins), 'builtin tracks')
